services:
  - type: web
    name: qat-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 5000
    autoDeploy: true
